package com.dharmesh.bizzbullindiaproject.common

object Constants {
    val timeOut: Long=30L

    //    Spinner Data
    const val SELECT = "Select"
    const val SELECT_HAND_USE = "Select regular hand usage"
    const val SELECT_BLOOD_GROUP = "Select your blood group"
    const val SELECT_PH = "Physically handicapped?"
    const val SELECT_SURGERY = "Any Surgeries/Treatments Undergone?"
    const val SELECT_HEALTHISSUES = "Any other Health Issues?"
    const val SELECT_UNHEALTHHABITS = "Any unhealthy habits?"
    const val SELECT_ACCOUNT_TYPE = "Select bank account type"
    const val SELECT_BUSINESSPLACETYPE = "Select business place type"
    const val OWNED = "Owned"
    const val LEASED = "Leased"
    const val RENTED = "Rented"
    const val SAVING = "Saving"
    const val CURRENT = "Current"
    const val RIGHT_HANDED = "Right-handed"
    const val LEFT_HANDED = "Left-handed"
    const val YES = "Yes"
    const val NO = "No"
    const val APLUS = "A+"
    const val OPLUS = "O+"
    const val BPLUS = "B+"
    const val ABPLUS = "A+"
    const val AMINUS = "A-"
    const val OMINUS = "O-"
    const val BMINUS = "B-"
    const val ABMINUS = "AB-"
    const val PVTLIMITED = "Pvt Limited"
    const val PARTNERSHIP = "Partnership"
    const val PROPRIETOR = "Proprietor"
    const val FOFO = "FOFO"
    const val FOCO = "FOCO"
    const val COFO = "COFO"
    var SHARED_PREFERENCES = "SHARED_PREFERENCES"
    var PREF_AUTH_KEY = "PREF_AUTH_KEY"
    var App_id = "App_id"
    var email = "email"
    var mobile = "mobile"
    var role_id = "role_id"
    var name = "name"
    var KEY = "key"
    var SECRET = "secret"
    var REGION = "region"
    var BUCKET = "bucket"
    var S3_URL = "s3_url"
}